version: 2

models:
  - name: create_deaths_table
    description: Table containing data from deaths table necessary for analysis
    columns:
      - name: date
        description: date of observation
        tests:
          - not_null
      - name: location
        description: country observation occured
        tests:
          - not_null

  - name: create_death_pct_variable
    description: creates new table and calculates 'death_percentage' 
    columns:
      - name: date
        description: date of observation
        tests:
          - not_null
      - name: location
        description: country observation ocurred
        tests:
          - not_null

  - name: total_cases_vs_pop
    description: creates new table and shows what percentage of the population has contracted covid on a given date
    columns:
      - name: date
        description: date of observation
        tests:
          - not_null
      - name: location
        description: country observation ocurred
        tests:
          - not_null
  
  - name: highest_infection_rate
    description: creates new table and Ranks countries by highest percentage of population infected with covid
    columns:
      - name: percent_population_infected
        description: calculated field displaying max value of percentage_population_infected for each country
        tests:
          - not_null
      - name: location
        description: country observation ocurred
        tests:
          - not_null

  - name: total_death_count_by_pop
    description: creates new table and shows countries with highest death count
    columns:
      - name: total_death_count
        description: total deaths
        tests:
          - not_null
  
  - name: total_deaths_by_continent
    description: creates new table and shows total deaths by continent
    columns:
      - name: total_death_count
        description: total deaths
        tests:
          - not_null
      - name: location
        description: continent observation ocurred
        tests:
          - not_null

  - name: global_covid_numbers
    description: creates new table and shows total new cases, total deaths, and total death percentage globally
    columns:
      - name: total_deaths
        description: total deaths globally
        tests:
          - not_null
      - name: total_cases
        description: total cases globally
        tests:
          - not_null
      - name: total_death_percentage
        description: total death percentage globally
        tests:
          - not_null

  - name: new_vaccinations_per_day
    description: Table containing data showing new vaccination per day for each country over time
    columns:
      - name: date
        description: date of observation
        tests:
          - not_null
      - name: location
        description: country observation occured
        tests:
          - not_null

  - name: cte_cumulative_vacc_pct_vacc
    description: CTE joining deaths and vaccination tables, creates cumulative vaccinations and cumulative percent of population vaccinated for each country
    columns:
      - name: location
        description: country observation occured
        tests:
          - not_null